export const ADD_COMPONENT_BOX = "ADD_COMPONENT_BOX";
export const UPDATE_ACTIVE_COMPONENT_BOX = "UPDATE_ACTIVE_COMPONENT_BOX";
export const GET_COMPONENT_BOXES = "GET_COMPONENT_BOXES";
export const CLEAR_COMPONENT_BOXES= "CLEAR_COMPONENT_BOXES";
export const UPDATE_ACTIVE_NAVIGATION_BUTTON = "UPDATE_ACTIVE_NAVIGATION_BUTTON";